// Shasta.
#include "Options.hpp"
using namespace shasta2;

// Standard library.
#include "array.hpp"
#include "stdexcept.hpp"
#include <thread>



Options::Options(int argc, char** argv) :
    CLI::App("Shasta2. Under development.")
{
    allow_config_extras(false);
    set_config("--config", "", "Specify a configuration file.");

    get_formatter()->column_width(20);

    addOptions();

    try {
        parse(argc, argv);
    } catch(const CLI::ParseError& e) {
         exit(e);
         if(e.get_name() == "CallForHelp") {
             isHelp = true;
         } else {
             throw runtime_error("Error parsing options.");
         }
    }

    // Adjust the numbers of threads, if necessary.
    if(threadCount == 0) {
        threadCount = std::thread::hardware_concurrency();
    }

}



void Options::addOptions()
{
    add_option("--input", inputFileNames,
        "Input fasta or fastq files (uncompressed)."
        )->capture_default_str();

    add_option("--max-anchor-repeat-length", maxAnchorRepeatLength,
        "Maximum number of copies of repeats of period 1, 2, 3,... allowed in an anchor sequence."
        )->capture_default_str();

    add_option("--simplify-max-iterationCount", simplifyMaxIterationCount,
        "Maximum number of assembly graph simplify iterations."
        )->capture_default_str();

    add_option("--bubble-cleanup-max-bubble-length",
       bubbleCleanupMaxBubbleLength,
       "Maximum bubble length for bubble cleanup."
       )->capture_default_str();

    add_option("--bubble-cleanup-min-common-count",
       bubbleCleanupMinCommonCount,
       "Minimum number of common oriented reads for bubble cleanup."
       )->capture_default_str();

    add_option("--find-superbubbles-max-distance",
        findSuperbubblesMaxDistance,
       "Maximum distance (number of BFS edges) when finding superbubbles."
       )->capture_default_str();

    add_option("--phasing-distance",
        phasingDistance,
       "Maximum bubble-bubble distance (number of edges) for phasing."
       )->capture_default_str();

    add_option("--phasing-min-coverage",
        phasingMinCoverage,
       "Minimum coverage generated by phasing."
       )->capture_default_str();



	// Options defined in OptionsDefine.hpp
	#define SHASTA2_OPTION_DEFINE(type, name, optionName, defaultValue, description) \
		add_option(optionName, name, description)->capture_default_str();
	#include "OptionsDefine.hpp"
	#undef SHASTA2_OPTION_DEFINE
}



// Constructor from a configuration file.
Options::Options(const string& fileName)
{

    allow_config_extras(false);
    set_config("--config", "", "Configuration file.");
    get_formatter()->column_width(20);

    addOptions();

    if(not fileName.empty()) {
        // Construct arguments "--config fileName".
        int argc = 3;
        const string name = "shasta2";
        const string keyword = "--config";
        char* arg0 = const_cast<char*>(name.c_str());
        char* arg1 = const_cast<char*>(keyword.c_str());
        char* arg2 = const_cast<char*>(fileName.c_str());
        const array<char*, 3> argv = {arg0, arg1, arg2};

        try {
            parse(argc, &argv.front());
        } catch(const CLI::ParseError& e) {
             exit(e);
             throw runtime_error("Error parsing options.");
        }
    }

    // Adjust the numbers of threads, if necessary.
    if(threadCount == 0) {
        threadCount = std::thread::hardware_concurrency();
    }
}



void Options::write(ostream& s) const
{
    s << config_to_str(true,true);
}
