// Shasta.
#include "Options.hpp"
using namespace shasta2;

// Standard library.
#include "array.hpp"
#include "stdexcept.hpp"
#include <thread>



Options::Options(int argc, char** argv) :
    CLI::App("Shasta2. Under development.")
{
    allow_config_extras(false);
    set_config("--config", "", "Specify a configuration file.");

    get_formatter()->column_width(20);

    addOptions();

    try {
        parse(argc, argv);
    } catch(const CLI::ParseError& e) {
         exit(e);
         if(e.get_name() == "CallForHelp") {
             isHelp = true;
         } else {
             throw runtime_error("Error parsing options.");
         }
    }

    // Adjust the numbers of threads, if necessary.
    if(threadCount == 0) {
        threadCount = std::thread::hardware_concurrency();
    }

}



void Options::addOptions()
{
    add_option("--input", inputFileNames,
        "Input fasta or fastq files (uncompressed)."
        )->capture_default_str();

    add_option("--min-read-length", minReadLength,
        "Read length cutoff."
        )->capture_default_str();

    add_option("--k", k,
        "Marker length"
        )->capture_default_str();

    add_option("--marker-density", markerDensity,
        "Marker density."
        )->capture_default_str();

    add_option("--max-marker-error-rate", maxMarkerErrorRate,
        "Maximum marker error rate. Reads with a higher marker error rate are not used."
        )->capture_default_str();

    add_option("--external-anchors-name", externalAnchorsName,
        "External anchors name. Must be an absolute path without the .toc/.data extensions."
        )->capture_default_str();

    add_option("--min-anchor-coverage", minAnchorCoverage,
        "Minimum anchor coverage."
        )->capture_default_str();

    add_option("--max-anchor-coverage", maxAnchorCoverage,
        "Maximum anchor coverage."
        )->capture_default_str();

    add_option("--max-anchor-repeat-length", maxAnchorRepeatLength,
        "Maximum number of copies of repeats of period 1, 2, 3,... allowed in an anchor sequence."
        )->capture_default_str();

    add_option("--min-anchor-graph-edge-coverage", minAnchorGraphEdgeCoverage,
        "Minimum anchor graph edge coverage."
        )->capture_default_str();

    add_option("--min-anchor-graph-continue-read-following-count", minAnchorGraphContinueReadFollowingCount,
        "Coverage threshold to continue read following during anchor graph edge creation."
        )->capture_default_str();

    add_option("--transitive-reduction-max-edge-coverage", transitiveReductionMaxEdgeCoverage,
        "Maximum coverage of an AnchorGraph edge subject to removal during transitive reduction."
        )->capture_default_str();

    add_option("--transitive-reduction-max-distance", transitiveReductionMaxDistance,
        "Maximum distance for transitive reduction of the AnchorGraph."
        )->capture_default_str();

    add_option("--a-drift", aDrift,
        "Constant allowed offset for offset consistency."
        )->capture_default_str();

    add_option("--b-drift", bDrift,
        "Constant factor for offset consistency."
        )->capture_default_str();

    add_option("--simplify-max-iterationCount", simplifyMaxIterationCount,
        "Maximum number of assembly graph simplify iterations."
        )->capture_default_str();

    add_option("--bubble-cleanup-max-bubble-length",
       bubbleCleanupMaxBubbleLength,
       "Maximum bubble length for bubble cleanup."
       )->capture_default_str();

    add_option("--bubble-cleanup-min-common-count",
       bubbleCleanupMinCommonCount,
       "Minimum number of common oriented reads for bubble cleanup."
       )->capture_default_str();

    add_option("--clustering-min-jaccard",
        clusteringMinJaccard,
       "Minimum Jaccard similarity for oriented read clustering."
       )->capture_default_str();

    add_option("--find-superbubbles-max-distance",
        findSuperbubblesMaxDistance,
       "Maximum distance (number of BFS edges) when finding superbubbles."
       )->capture_default_str();

    add_option("--simplify-superbubble-min-coverage",
        simplifySuperbubbleMinCoverage,
       "Minimum coverage when simplifying superbubbles."
       )->capture_default_str();

    add_option("--simplify-superbubble-max-offset",
        simplifySuperbubbleMaxOffset,
       "Maximum offset when simplifying superbubbles."
       )->capture_default_str();

    add_option("--phasing-distance",
        phasingDistance,
       "Maximum bubble-bubble distance (number of edges) for phasing."
       )->capture_default_str();

    add_option("--phasing-min-degree",
        phasingMinDegree,
       "Minimum degree for phasing graph vertices."
       )->capture_default_str();

    add_option("--phasing-min-coverage",
        phasingMinCoverage,
       "Minimum coverage generated by phasing."
       )->capture_default_str();



	// Options defined in OptionsDefine.hpp
	#define SHASTA2_OPTION_DEFINE(type, name, optionName, defaultValue, description) \
		add_option(optionName, name, description)->capture_default_str();
	#include "OptionsDefine.hpp"
	#undef SHASTA2_OPTION_DEFINE
}



// Constructor from a configuration file.
Options::Options(const string& fileName)
{

    allow_config_extras(false);
    set_config("--config", "", "Configuration file.");
    get_formatter()->column_width(20);

    addOptions();

    // Construct arguments "--config fileName".
    int argc = 3;
    const string name = "shasta2";
    const string keyword = "--config";
    char* arg0 = const_cast<char*>(name.c_str());
    char* arg1 = const_cast<char*>(keyword.c_str());
    char* arg2 = const_cast<char*>(fileName.c_str());
    const array<char*, 3> argv = {arg0, arg1, arg2};

    try {
        parse(argc, &argv.front());
    } catch(const CLI::ParseError& e) {
         exit(e);
         throw runtime_error("Error parsing options.");
    }

    // Adjust the numbers of threads, if necessary.
    if(threadCount == 0) {
        threadCount = std::thread::hardware_concurrency();
    }
}



void Options::write(ostream& s) const
{
    s << config_to_str(true,true);
}
